insert into user (user_id, name, sure_name) values (1, "Дмитрий", "Бабанин");
insert into account (account, user_id) values (5, 1);
insert into user (user_id, name, sure_name) values (2, "Никита", "Шнуров");
insert into account (account, user_id) values (9, 2);
insert into user (user_id, name, sure_name) values (3, "Женя", "Масколевич");
insert into account (account, user_id) values (10, 3);
insert into user (user_id, name, sure_name) values (4, "Наталья", "Ростова");
insert into account (account, user_id) values (7, 4);
insert into user (user_id, name, sure_name) values (5, "Кристина", "Венкова");
insert into account (account, user_id) values (6, 5);
insert into user (user_id, name, sure_name) values (6, "Дарья", "Михайлова");
insert into account (account, user_id) values (5, 6);
insert into user (user_id, name, sure_name) values (7, "Дмитрий", "Ловцов");
insert into account (account, user_id) values (10, 7);
insert into user (user_id, name, sure_name) values (8, "Никита", "Шевяков");
insert into account (account, user_id) values (3, 8);
insert into user (user_id, name, sure_name) values (9, "Женя", "Воронов");
insert into account (account, user_id) values (2, 9);
insert into user (user_id, name, sure_name) values (10, "Наталья", "Кларкова");
insert into account (account, user_id) values (1, 10);